//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZU.JCZD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string CompName { get; set; }
        public string Address { get; set; }
        public string CompEmail { get; set; }
        public string CompUrl { get; set; }
        public string Detail { get; set; }
    }
}
