//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZZU.JCZD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfoSet
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string UserPass { get; set; }
        public Nullable<System.DateTime> SubTime { get; set; }
        public Nullable<System.DateTime> ModifTime { get; set; }
        public string Phone { get; set; }
        public string Detail { get; set; }
        public int CompId { get; set; }
        public int RoleId { get; set; }
        public string RealName { get; set; }
        public string Image { get; set; }
        public bool DelFlag { get; set; }
    }
}
